name: hopelinker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo.png
  - assets/logomini.png
  - assets/html/leafletmap.html
  - assets/js/
  - assets/mappage/homeicon.png
  - assets/mappage/forum.png
  - assets/mappage/chatbot.png
  - assets/mappage/profile.png
  - assets/mappage/homebackground.png
  - assets/mappage/homedesign.png
  - assets/mappage/lower-bar.png
  - assets/logosidetitle.png
  - assets/loadinglogo.png
  - assets/mappage/homebackgroundCopy.png
  - assets/blue_ellipse.png